{% set version = "8.8.0" %}

package:
  name: esmpy
  version: {{ version }}

source:
  url: https://github.com/esmf-org/esmf/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f89327428aeef6ad34660b5b78f30d1c55ec67efb8f7df1991fdaa6b1eb3a27c
  patches:
    - 0001-remove-setuptools-git-versioning.patch
    - 0002-win-loading.patch

build:
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - esmf {{ version }} nompi_*
    - pip
    - setuptools >=41
    - setuptools-git-versioning
    # for testing
    - make
    - numpy
    - pytest
    - pytest-json-report
  run:
    # newer python so we don't need importlib-metadata
    - python >={{ python_min }}
    - numpy >=1.19,<3
    # skipping setuptools-git-versioning because this is really just a host dependency
    - esmf {{ version }}

test:
  imports:
    - esmpy
  requires:
    - pip
    - pytest-json-report
    - esmf * mpi_mpich_*
    - python {{ python_min }}
  source_files:
    - src/addon/esmpy/examples
  commands:
    - pip check

about:
  home: http://earthsystemmodeling.org/esmpy/
  license: NCSA
  license_file: LICENSE
  summary: ESMPy is a Python interface to the Earth System Modeling Framework (ESMF) regridding utility.
  dev_url: https://github.com/esmf-org/esmf/tree/develop/src/addon/esmpy
  doc_url: https://earthsystemmodeling.org/esmpy_doc/nightly/develop/html/

extra:
  recipe-maintainers:
    - zklaus
    - ocefpaf
    - rokuingh
    - xylar
    - billsacks
