{% set version = "8.2.0" %}
{% set ver = version.replace(".", "_") %}
{% set build = 0 %}

# recipe-lint fails if mpi is undefined
{% set mpi = mpi or 'nompi' %}

{% if mpi == 'mpich' %}
# prioritize mpich variant, which was previously the only option, via build number
{% set build = build + 100 %}
{% endif %}

package:
  name: esmpy
  version: {{ version }}

source:
  url: https://github.com/esmf-org/esmf/archive/ESMF_{{ ver }}/esmf_{{ ver }}_src.tar.gz
  sha256: 3693987aba2c8ae8af67a0e222bea4099a48afe09b8d3d334106f9d7fc311485
  patches:
    - 0000-setup.py-version.patch

build:
  number: {{ build }}
  skip: true  # [win]

  # add build string so packages can depend on
  # mpi or nompi variants explicitly:
  # `esmf * mpi_mpich_*` for mpich
  # `esmf * mpi_*` for any mpi
  # `esmf * nompi_*` for no mpi

  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: {{ mpi_prefix }}_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ build }}

requirements:
  host:
    - python
    - numpy
    - esmf {{ version }} {{ mpi_prefix }}_*
    - nose
    - {{ mpi }}  # [mpi != 'nompi']
    - mpi4py  # [mpi != 'nompi']
  run:
    - python
    - numpy
    - esmf {{ version }} {{ mpi_prefix }}_*
    - {{ mpi }}  # [mpi != 'nompi']
    - mpi4py  # [mpi != 'nompi']
    - openssh  # [mpi == 'openmpi']

test:
  imports:
    - ESMF

about:
  home: http://earthsystemmodeling.org/esmpy/
  license: NCSA
  license_file: LICENSE
  summary: ESMPy is a Python interface to the Earth System Modeling Framework (ESMF) regridding utility.

extra:
  recipe-maintainers:
    - ocefpaf
    - rokuingh
    - xylar
