{% set version = "8.4.0" %}
{% set build = 0 %}

# recipe-lint fails if mpi is undefined
{% set mpi = mpi or 'nompi' %}

{% if mpi == 'mpich' %}
# prioritize mpich variant, which was previously the only option, via build number
{% set build = build + 100 %}
{% endif %}

package:
  name: esmpy
  version: {{ version }}

source:
  url: https://github.com/esmf-org/esmf/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 28531810bf1ae78646cda6494a53d455d194400f19dccd13d6361871de42ed0f
  patches:
    - 0001-remove-tests-for-no-pio.patch  # [mpi == 'nompi']

build:
  number: {{ build }}
  skip: true  # [win]

  # add build string so packages can depend on
  # mpi or nompi variants explicitly:
  # `esmf * mpi_mpich_*` for mpich
  # `esmf * mpi_*` for any mpi
  # `esmf * nompi_*` for no mpi

  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: {{ mpi_prefix }}_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ build }}

requirements:
  host:
    - python
    - numpy
    - esmf {{ version }} {{ mpi_prefix }}_*
    - nose
    - {{ mpi }}  # [mpi != 'nompi']
    - mpi4py  # [mpi != 'nompi']
  run:
    - python
    - numpy
    - esmf {{ version }} {{ mpi_prefix }}_*
    - {{ mpi }}  # [mpi != 'nompi']
    - mpi4py  # [mpi != 'nompi']
    - openssh  # [mpi == 'openmpi']

test:
  imports:
    - ESMF

about:
  home: http://earthsystemmodeling.org/esmpy/
  license: NCSA
  license_file: LICENSE
  summary: ESMPy is a Python interface to the Earth System Modeling Framework (ESMF) regridding utility.

extra:
  recipe-maintainers:
    - zklaus
    - ocefpaf
    - rokuingh
    - xylar
