{% set version = "8.4.1" %}
{% set build = 0 %}

# recipe-lint fails if mpi is undefined
{% set mpi = mpi or 'nompi' %}

{% if mpi == 'mpich' %}
# prioritize mpich variant, which was previously the only option, via build number
{% set build = build + 100 %}
{% endif %}

package:
  name: esmpy
  version: {{ version }}

source:
  url: https://github.com/esmf-org/esmf/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1b54cee91aacaa9df400bd284614cbb0257e175f6f3ec9977a2d991ed8aa1af6
  patches:
    - 0001-skip-problematic-test.patch
    - remove-fragments.patch
    - win-loading.patch

build:
  number: {{ build }}

  # add build string so packages can depend on
  # mpi or nompi variants explicitly:
  # `esmf * mpi_mpich_*` for mpich
  # `esmf * mpi_*` for any mpi
  # `esmf * nompi_*` for no mpi

  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: {{ mpi_prefix }}_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ build }}

requirements:
  build:
    - make  # [unix]
    - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - make  # [unix]
    - python
    - pytest
    - pytest-json-report
    - netcdf4
    - numpy
    - esmf {{ version }} {{ mpi_prefix }}_*
    - nose
    - {{ mpi }}  # [mpi != 'nompi']
    - mpi4py  # [mpi != 'nompi']
    - pip
    - setuptools-git-versioning
  run:
    - python
    - numpy
    - esmf {{ version }} {{ mpi_prefix }}_*
    - {{ mpi }}  # [mpi != 'nompi']
    - mpi4py  # [mpi != 'nompi']
    - openssh  # [mpi == 'openmpi']

test:
  imports:
    - esmpy
  requires:
    - pip
    - pytest-json-report
  commands:
    - pip check
    # - make test
    # - python -m pytest -vs  # [mpi == 'nompi']
    # - mpiexec -np 1 python -m pytest -vs  # [mpi != 'nompi']
    # - mpiexec -np 2 python -m pytest -vs  # [mpi != 'nompi']

about:
  home: http://earthsystemmodeling.org/esmpy/
  license: NCSA
  license_file: LICENSE
  summary: ESMPy is a Python interface to the Earth System Modeling Framework (ESMF) regridding utility.

extra:
  recipe-maintainers:
    - zklaus
    - ocefpaf
    - rokuingh
    - xylar
