{% set version = "8.4.1" %}

package:
  name: esmpy
  version: {{ version }}

source:
  url: https://github.com/esmf-org/esmf/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1b54cee91aacaa9df400bd284614cbb0257e175f6f3ec9977a2d991ed8aa1af6
  patches:
    - 0001-skip-problematic-test.patch
    - remove-fragments.patch
    - win-loading.patch

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - esmf {{ version }} nompi_*
    - pip
    - setuptools >=41
    - setuptools-git-versioning
  run:
    - python >=3.7
    - numpy
    - esmf {{ version }}

test:
  imports:
    - esmpy
  requires:
    - pip
    - pytest-json-report
  commands:
    - pip check

about:
  home: http://earthsystemmodeling.org/esmpy/
  license: NCSA
  license_file: LICENSE
  summary: ESMPy is a Python interface to the Earth System Modeling Framework (ESMF) regridding utility.

extra:
  recipe-maintainers:
    - zklaus
    - ocefpaf
    - rokuingh
    - xylar
