{% set version = "8.7.0" %}

package:
  name: esmpy
  version: {{ version }}

source:
  url: https://github.com/esmf-org/esmf/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d7ab266e2af8c8b230721d4df59e61aa03c612a95cc39c07a2d5695746f21f56
  patches:
    - 0001-remove-setuptools-git-versioning.patch
    - 0002-win-loading.patch
    - 0003-change-data-url.patch

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - esmf {{ version }} nompi_*
    - pip
    - setuptools >=41
    - setuptools-git-versioning
    # for testing
    - make
    - numpy
    - pytest
    - pytest-json-report
  run:
    # newer python so we don't need importlib-metadata
    - python >=3.8
    - numpy
    # skipping setuptools-git-versioning because this is really just a host dependency
    - esmf {{ version }}

test:
  imports:
    - esmpy
  requires:
    - pip
    - pytest-json-report
    - esmf {{ version }} mpi_mpich_*
  source_files:
    - src/addon/esmpy/examples
  commands:
    - pip check
    - mpiexec -np 1 python -m pytest -vs
    - mpiexec -np 2 python -m pytest -vs
    - mpiexec -np 2 python src/addon/esmpy/examples/test_examples.py

about:
  home: http://earthsystemmodeling.org/esmpy/
  license: NCSA
  license_file: LICENSE
  summary: ESMPy is a Python interface to the Earth System Modeling Framework (ESMF) regridding utility.
  dev_url: https://github.com/esmf-org/esmf/tree/develop/src/addon/esmpy
  doc_url: https://earthsystemmodeling.org/esmpy_doc/nightly/develop/html/

extra:
  recipe-maintainers:
    - zklaus
    - ocefpaf
    - rokuingh
    - xylar
    - billsacks
